### PR TITLE
Total rewrite of this package

### PR DESCRIPTION
**Pull request by nilsbore**
Since this is not used and I have a much better system in place now with the same functionality I though we might as well replace the old stuff with this new thing that works much better in practice, with no intermediate storing of images etc.

### CODE REVIEW

**Comment by nilsbore** [comment]
@hawesie @marc-hanheide I thought that this could be very useful as a standalone package and it basically replicates the behaviour of the previous data_compression so it might as well go here. The question is how you wanted to integrate with mongodb and if it makes sense to put it here with that in mind?

**Comment by hawesie** [comment]
Does it generate messages that can be stored then played back as in rosbag? If so, then we can just log them using mongodb_log.=

**Comment by nilsbore** [comment]
Yes, that was the idea. I wasn't aware that mongodb had this kind of ability already so I created a demonstrator with rosbag. But it should be easy enough to make a mongodv

**Comment by nilsbore** [comment]
Sorry, typing on my phone. It seems like it would be easy to make a similar package for mongodb then.

**Comment by cdondrup** [comment]
Just tried to build it. Two things so far:
1. You're downloading `libav_trunk` using catkin (cmake), I think a git submodule would be the more standard solution here.
2. `libav_trunk` needs `libx264` for which there is no rosdep definition if I'm not mistaken.

Apart from that it builds fine.

**Comment by marc-hanheide** [comment]
For libx264 I suggest to submit a pull request against ros/rosdistro. They are usually quick in accepting these for rosdep stuff

**Comment by nilsbore** [comment]
Allright, @cdondrup, thanks for testing! @marc-hanheide Wasn't the idea that we could also add that to our own sources? Would the pull request be adding something to this file then: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml ?

**Comment by marc-hanheide** [comment]
On 19 Oct 2014 18:16, "Nils Bore" notifications@github.com wrote:

> Would the pull request be adding something to this file then:
> https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml ?

Yes, indeed. We could have our own rosdep (and we do for a few packages
that are not officially available such as Mira), but for those more general
ones it's better to share them with the community straight away.

**Comment by nilsbore** [comment]
Ok, I've changed libav to be a submodule and submitted a pull request https://github.com/ros/rosdistro/pull/6039 to rosdistro to include libx264.

**Pull request merged**
