### PR TITLE
make sure dependencies are working correctly and adding deps for libavdevice etc.

### PR DESCRIPTION
**Pull request by marc-hanheide**
check https://github.com/strands-project/data_compression/issues/62#issuecomment-75855712

### CODE REVIEW

**Comment by marc-hanheide** [comment]
this is doomed to fail until https://github.com/strands-project/rosdistro/pull/370 is merged

**Comment by marc-hanheide** [comment]
OK, @nilsbore, this PR is now modified so it works for me perfectly fine without any additional requirements. See if this does the trick for you, too.

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
it works :-)

**Comment by nilsbore** [comment]
@marc-hanheide I will try but I again suspect that it will work for the devel build but not for release (when building `catkinized_libav` in isolation before `libav_image_transport`). Did you try that as well?

**Comment by marc-hanheide** [comment]
trying...

**Comment by marc-hanheide** [comment]
catkin_make_isolated worked, too

**Comment by nilsbore** [comment]
lo and behold, it actually seems to work here now.

**Comment by marc-hanheide** [comment]
if you agree then merge this and I'll re-release to see what happens then

**Comment by nilsbore** [comment]
I compiled `catkinized_libav`, installed it and compiled `libav_image_transport` using the installed version. Unless I'm doing something wrong it should work.

**Comment by nilsbore** [comment]
That would be really cool! Then we know how to do this the right way for future libraries.

**Comment by marc-hanheide** [comment]
Then let's give it a shot and release it?

**Comment by nilsbore** [comment]
Yep!

**Comment by marc-hanheide** [comment]
OK, so jenkins built both `catkinized_libav` and `libav_image_transport`. That's the critical bit, so I'm happy and close this until somebody tells me it breaks. The release process shall be completed in 30 minutes or so. Yeah!

**Pull request merged**
